### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by irvingreid** [mozilla/iacomus#1]
I tried to use your github.io deployment of iacomus to render a .json config file in my own github space:

http://vitillo.github.io/iacomus/resources/public/index.html?config=https://raw.githubusercontent.com/irvingreid/iacomus/master/resources/public/addon_perf.json

and got the message "The configuration file is either missing or invalid!"
I'd much rather have the actual error details than a dancing monkey...

**Comment by vitillo** [comment]
Irving, I can see the error in the console, i.e.

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/irvingreid/iacomus/master/resources/public/addon_perf.json. This can be fixed by moving the resource to the same domain or enabling CORS."

Unfortunately for the dashboard to work without redeploying it, the server serving config.json needs to allow Cross-Origin requests like we do for e.g. our datasets on S3.

**Comment by irvingreid** [comment]
OK. I was hoping there would be an easy way to just drop a config .json anywhere (such as in the S3 bucket) and not need to redeploy the application.

**Comment by vitillo** [comment]
I am not aware of a javascript only way to go around the same origin policy but you could store the config.json in our S3 bucket which has CORS enabled.
